name: Unittest - Variable

on:
    push:
        branches:
            - akhil-branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        
        - name: Change to tests directory
          run: cd tests            
          
        - name: Run unittests
          run: python test_Gradient.py
        
        - name: Notify on success
          if: success()
          run: echo "Unit tests passed successfully"
        
        - name: Notify on failure
          if: failure()
          run: echo "Unit tests failed"